# Generated by Django 5.1.2 on 2024-10-20 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_wallpaper',
            name='zip_file',
            field=models.FileField(null=True, upload_to='uploads/zips/'),
        ),
        migrations.CreateModel(
            name='ExtractedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('zip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_files', to='auth_app.post_wallpaper')),
            ],
        ),
    ]
