# Generated by Django 5.1.2 on 2024-10-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_post_wallpaper_user_userupload_uploadedimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userupload',
            old_name='created_at',
            new_name='uploaded_at',
        ),
    ]
