# Generated by Django 5.1.2 on 2025-02-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_userupload_user_post_wallpaper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_wallpaper',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
