# Generated by Django 3.2 on 2025-05-11 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0006_alter_post_wallpaper_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_wallpaper',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
