# Generated by Django 3.2 on 2025-05-11 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_post_wallpaper_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_likes', to='auth_app.post_wallpaper')),
            ],
            options={
                'unique_together': {('post', 'session_key')},
            },
        ),
    ]
