# Generated by Django 3.2 on 2025-05-11 11:48

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_anonymouslike'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post_wallpaper',
            managers=[
                ('anonymous_likes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post_wallpaper',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
